"""empty message

Revision ID: 24fe931af5a2
Revises: 1bca4ad3426b
Create Date: 2025-05-20 16:07:29.250281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24fe931af5a2'
down_revision = '1bca4ad3426b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ldap_enabled', sa.Boolean(), nullable=True),
    sa.Column('ldap_server', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settings')
    # ### end Alembic commands ###
