"""empty message

Revision ID: 343da8d724a4
Revises: 9b7833a41811
Create Date: 2025-06-16 11:53:31.186062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '343da8d724a4'
down_revision = '9b7833a41811'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('guest', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.drop_column('guest')

    # ### end Alembic commands ###
