"""empty message

Revision ID: 3f5b6564ca07
Revises: be575b8882a3
Create Date: 2025-05-21 12:20:34.739769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f5b6564ca07'
down_revision = 'be575b8882a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('readers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gateway_configs', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('readers', schema=None) as batch_op:
        batch_op.drop_column('gateway_configs')

    # ### end Alembic commands ###
