"""empty message

Revision ID: 49882eb44958
Revises: 85e0c194decf
Create Date: 2025-05-21 15:00:00.966941

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '49882eb44958'
down_revision = '85e0c194decf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.alter_column('badge_uid',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=32),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.alter_column('badge_uid',
               existing_type=sa.String(length=32),
               type_=mysql.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
