"""empty message

Revision ID: 545a2a16f4c6
Revises: 49882eb44958
Create Date: 2025-05-22 09:35:06.353328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '545a2a16f4c6'
down_revision = '49882eb44958'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('openid_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('openid_client_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('openid_client_secret', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('server_metadata_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_column('server_metadata_url')
        batch_op.drop_column('openid_client_secret')
        batch_op.drop_column('openid_client_id')
        batch_op.drop_column('openid_enabled')

    # ### end Alembic commands ###
