"""empty message

Revision ID: 732a49732466
Revises: c9338d17dcb5
Create Date: 2025-05-20 17:10:19.648023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '732a49732466'
down_revision = 'c9338d17dcb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('email')

    # ### end Alembic commands ###
