"""empty message

Revision ID: 7f3a8cb99d8c
Revises: 2bdeeba76981
Create Date: 2025-05-22 17:08:05.591245

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7f3a8cb99d8c'
down_revision = '2bdeeba76981'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('badges', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'roles', ['role'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('users_ibfk_1', type_='foreignkey')
        batch_op.drop_column('role')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('users_ibfk_1', 'roles', ['role'], ['id'])

    with op.batch_alter_table('badges', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('role')

    # ### end Alembic commands ###
