"""empty message

Revision ID: 85e0c194decf
Revises: cff049a07436
Create Date: 2025-05-21 14:50:17.542423

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '85e0c194decf'
down_revision = 'cff049a07436'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('badge_uid', sa.Integer(), nullable=True))
        batch_op.drop_column('uid')
        batch_op.drop_column('badge_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('badge_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('uid', mysql.VARCHAR(length=32), nullable=True))
        batch_op.drop_column('badge_uid')

    # ### end Alembic commands ###
