"""empty message

Revision ID: a2043b2e9532
Revises: 545a2a16f4c6
Create Date: 2025-05-22 09:36:44.812427

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a2043b2e9532'
down_revision = '545a2a16f4c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('openid_metadata_url', sa.String(length=255), nullable=True))
        batch_op.drop_column('server_metadata_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('server_metadata_url', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('openid_metadata_url')

    # ### end Alembic commands ###
