"""v1.0.1

Revision ID: a478975d776b
Revises: 
Create Date: 2025-06-27 16:24:34.011285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a478975d776b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(length=64), nullable=False),
    sa.Column('git_url', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_addons'))
    )
    op.create_table('gateways',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('configs', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gateways'))
    )
    op.create_table('plugins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(length=64), nullable=False),
    sa.Column('configs', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plugins'))
    )
    op.create_table('readers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('pos_x', sa.Integer(), nullable=True),
    sa.Column('pos_y', sa.Integer(), nullable=True),
    sa.Column('gateway', sa.String(length=64), nullable=True),
    sa.Column('gateway_configs', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_readers')),
    sa.UniqueConstraint('name', name=op.f('uq_readers_name'))
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('access_start', sa.Time(), nullable=True),
    sa.Column('access_end', sa.Time(), nullable=True),
    sa.Column('access_days', sa.String(length=7), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('name', name=op.f('uq_roles_name'))
    )
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enable_add_user', sa.Boolean(), nullable=True),
    sa.Column('ldap_enabled', sa.Boolean(), nullable=True),
    sa.Column('ldap_server', sa.String(length=255), nullable=True),
    sa.Column('ldap_base', sa.String(length=255), nullable=True),
    sa.Column('ldap_admin_filter', sa.String(length=255), nullable=True),
    sa.Column('openid_enabled', sa.Boolean(), nullable=True),
    sa.Column('openid_client_id', sa.String(length=255), nullable=True),
    sa.Column('openid_client_secret', sa.String(length=255), nullable=True),
    sa.Column('openid_metadata_url', sa.String(length=255), nullable=True),
    sa.Column('smtp_server', sa.String(length=255), nullable=True),
    sa.Column('smtp_from_email', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_settings'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('from_ldap', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_table('badges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('deactivation_date', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('guest_name', sa.String(length=64), nullable=True),
    sa.Column('company_name', sa.String(length=64), nullable=True),
    sa.Column('role', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role'], ['roles.id'], name=op.f('fk_badges_role_roles')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_badges_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_badges'))
    )
    with op.batch_alter_table('badges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_badges_uid'), ['uid'], unique=True)

    op.create_table('logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_time', sa.DateTime(), nullable=True),
    sa.Column('reader_id', sa.Integer(), nullable=True),
    sa.Column('badge_uid', sa.String(length=32), nullable=True),
    sa.Column('user_name', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('guest', sa.String(length=128), nullable=True),
    sa.Column('result', sa.String(length=16), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['reader_id'], ['readers.id'], name=op.f('fk_logs_reader_id_readers')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_logs_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_logs'))
    )
    op.create_table('role_readers',
    sa.Column('role', sa.Integer(), nullable=False),
    sa.Column('reader_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['reader_id'], ['readers.id'], name=op.f('fk_role_readers_reader_id_readers')),
    sa.ForeignKeyConstraint(['role'], ['roles.id'], name=op.f('fk_role_readers_role_roles')),
    sa.PrimaryKeyConstraint('role', 'reader_id', name=op.f('pk_role_readers'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('role_readers')
    op.drop_table('logs')
    with op.batch_alter_table('badges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_badges_uid'))

    op.drop_table('badges')
    op.drop_table('users')
    op.drop_table('settings')
    op.drop_table('roles')
    op.drop_table('readers')
    op.drop_table('plugins')
    op.drop_table('gateways')
    op.drop_table('addons')
    # ### end Alembic commands ###
