"""empty message

Revision ID: d1d6b1a60efc
Revises: 15ebd7b5e8b9
Create Date: 2025-05-22 16:31:45.416537

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd1d6b1a60efc'
down_revision = '15ebd7b5e8b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('badges', schema=None) as batch_op:
        batch_op.add_column(sa.Column('guest_name', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('company_name', sa.String(length=64), nullable=True))
        batch_op.alter_column('uid',
               existing_type=mysql.VARCHAR(length=32),
               type_=sa.String(length=64),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('badges', schema=None) as batch_op:
        batch_op.alter_column('uid',
               existing_type=sa.String(length=64),
               type_=mysql.VARCHAR(length=32),
               existing_nullable=False)
        batch_op.drop_column('company_name')
        batch_op.drop_column('guest_name')

    # ### end Alembic commands ###
