"""empty message

Revision ID: d8296c1cf74c
Revises: 5219dbf3dd07
Create Date: 2025-05-27 10:08:59.575763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8296c1cf74c'
down_revision = '5219dbf3dd07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('readers', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_readers_name'), ['name'])

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('access_days', sa.String(length=20), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_roles_name'), ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_roles_name'), type_='unique')
        batch_op.drop_column('access_days')

    with op.batch_alter_table('readers', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_readers_name'), type_='unique')

    # ### end Alembic commands ###
