"""empty message

Revision ID: da68c313b15a
Revises: d8296c1cf74c
Create Date: 2025-05-27 13:27:35.437695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da68c313b15a'
down_revision = 'd8296c1cf74c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.alter_column('access_days',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=7),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.alter_column('access_days',
               existing_type=sa.String(length=7),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###
